version: '3.7'

services:
  redis:
    container_name: redis
    image: redis:5
    networks:
      - webnet
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      - POSTGRES_DB=messenger
      - PGDATA=/data
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data
networks:
  webnet:
volumes:
  pgdata:
